# Generated by Django 5.1 on 2024-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
    ]
